info:
  namespace: customcrops
items:
  broccoli_seeds:
    enabled: true
    display_name: "Broccoli Seeds"
    lore:
      - "&7&oPlant these seeds to grow broccoli."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/broccoli/seeds # Link to ItemsAdder/contents/textures/item/broccoli/{filename}.png
  broccoli_stage_1:
    enabled: true
    display_name: broccoli_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/broccoli/stage_1 # Link to ItemsAdder/contents/textures/item/broccoli/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
  broccoli_stage_2:
    enabled: true
    display_name: broccoli_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/broccoli/stage_2 # Link to ItemsAdder/contents/textures/item/broccoli/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
  broccoli_stage_3:
    enabled: true
    display_name: broccoli_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/broccoli/stage_3 # Link to ItemsAdder/contents/textures/item/broccoli/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
  broccoli_stage_4:
    enabled: true
    display_name: broccoli_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/broccoli/stage_4 # Link to ItemsAdder/contents/textures/item/broccoli/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true