info:
  namespace: customcrops
items:
  cabbage_seeds:
    enabled: true
    display_name: "Cabbage Seeds"
    lore:
      - "&7&oPlant these seeds to grow cabbages."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/cabbage/seeds # Link to ItemsAdder/contents/textures/item/cabbage/{filename}.png

  cabbage_stage_1:
    enabled: true
    display_name: cabbage_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/cabbage/stage_1 # Link to ItemsAdder/contents/textures/item/cabbage/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  cabbage_stage_2:
    enabled: true
    display_name: cabbage_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/cabbage/stage_2 # Link to ItemsAdder/contents/textures/item/cabbage/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  cabbage_stage_3:
    enabled: true
    display_name: cabbage_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/cabbage/stage_3 # Link to ItemsAdder/contents/textures/item/cabbage/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  cabbage_stage_4:
    enabled: true
    display_name: cabbage_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/cabbage/stage_4 # Link to ItemsAdder/contents/textures/item/cabbage/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true