info:
  namespace: customcrops
items:
  celery_seeds:
    enabled: true
    display_name: "Celery Seeds"
    lore:
      - "&7&oPlant these seeds to grow celery."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/celery/seeds # Link to ItemsAdder/contents/textures/item/celery/{filename}.png

  celery_stage_1:
    enabled: true
    display_name: celery_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/celery/stage_1 # Link to ItemsAdder/contents/textures/item/celery/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  celery_stage_2:
    enabled: true
    display_name: celery_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/celery/stage_2 # Link to ItemsAdder/contents/textures/item/celery/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  celery_stage_3:
    enabled: true
    display_name: celery_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/celery/stage_3 # Link to ItemsAdder/contents/textures/item/celery/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  celery_stage_4:
    enabled: true
    display_name: celery_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/celery/stage_4 # Link to ItemsAdder/contents/textures/item/celery/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true