info:
  namespace: customcrops
items:
  garlic_seeds:
    enabled: true
    display_name: "Garlic Seeds"
    lore:
      - "&7&oPlant these seeds to grow garlic."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/garlic/seeds # Link to ItemsAdder/contents/textures/item/garlic/{filename}.png

  garlic_stage_1:
    enabled: true
    display_name: garlic_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/garlic/stage_1 # Link to ItemsAdder/contents/textures/item/garlic/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  garlic_stage_2:
    enabled: true
    display_name: garlic_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/garlic/stage_2 # Link to ItemsAdder/contents/textures/item/garlic/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  garlic_stage_3:
    enabled: true
    display_name: garlic_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/garlic/stage_3 # Link to ItemsAdder/contents/textures/item/garlic/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  garlic_stage_4:
    enabled: true
    display_name: garlic_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/garlic/stage_4 # Link to ItemsAdder/contents/textures/item/garlic/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true