info:
  namespace: customcrops
items:
  grape_seeds:
    enabled: true
    display_name: "Grape Seeds"
    lore:
      - "&7&oPlant these seeds to grow grapes."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/grape/seeds # Link to ItemsAdder/contents/textures/item/grape/{filename}.png

  grape_stage_1:
    enabled: true
    display_name: grape_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/grape/stage_1 # Link to ItemsAdder/contents/textures/item/grape/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  grape_stage_2:
    enabled: true
    display_name: grape_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/grape/stage_2 # Link to ItemsAdder/contents/textures/item/grape/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  grape_stage_3:
    enabled: true
    display_name: grape_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/grape/stage_3 # Link to ItemsAdder/contents/textures/item/grape/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  grape_stage_4:
    enabled: true
    display_name: grape_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/grape/stage_4 # Link to ItemsAdder/contents/textures/item/grape/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true