info:
  namespace: customcrops
items:
  greenbean_seeds:
    enabled: true
    display_name: "Green Bean Seeds"
    lore:
      - "&7&oPlant these seeds to grow green beans."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/greenbean/seeds # Link to ItemsAdder/contents/textures/item/greenbean/{filename}.png

  greenbean_stage_1:
    enabled: true
    display_name: greenbean_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/greenbean/stage_1 # Link to ItemsAdder/contents/textures/item/greenbean/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  greenbean_stage_2:
    enabled: true
    display_name: greenbean_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/greenbean/stage_2 # Link to ItemsAdder/contents/textures/item/greenbean/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  greenbean_stage_3:
    enabled: true
    display_name: greenbean_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/greenbean/stage_3 # Link to ItemsAdder/contents/textures/item/greenbean/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  greenbean_stage_4:
    enabled: true
    display_name: greenbean_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/greenbean/stage_4 # Link to ItemsAdder/contents/textures/item/greenbean/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true