info:
  namespace: customcrops
items:
  hops_seeds:
    enabled: true
    display_name: "Hops Seeds"
    lore:
      - "&7&oPlant these seeds to grow hops."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/hops/seeds # Link to ItemsAdder/contents/textures/item/hops/{filename}.png

  hops_stage_1:
    enabled: true
    display_name: hops_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/hops/stage_1 # Link to ItemsAdder/contents/textures/item/hops/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  hops_stage_2:
    enabled: true
    display_name: hops_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/hops/stage_2 # Link to ItemsAdder/contents/textures/item/hops/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  hops_stage_3:
    enabled: true
    display_name: hops_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/hops/stage_3 # Link to ItemsAdder/contents/textures/item/hops/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  hops_stage_4:
    enabled: true
    display_name: hops_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/hops/stage_4 # Link to ItemsAdder/contents/textures/item/hops/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true