info:
  namespace: customcrops
items:
  leek_seeds:
    enabled: true
    display_name: "Leek"
    lore:
      - "&7&oPlant these seeds to grow leek."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/leek/seeds # Link to ItemsAdder/contents/textures/item/leek/{filename}.png

  leek_stage_1:
    enabled: true
    display_name: leek_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/leek/stage_1 # Link to ItemsAdder/contents/textures/item/leek/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  leek_stage_2:
    enabled: true
    display_name: leek_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/leek/stage_2 # Link to ItemsAdder/contents/textures/item/leek/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  leek_stage_3:
    enabled: true
    display_name: leek_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/leek/stage_3 # Link to ItemsAdder/contents/textures/item/leek/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  leek_stage_4:
    enabled: true
    display_name: leek_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/leek/stage_4 # Link to ItemsAdder/contents/textures/item/leek/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true