info:
  namespace: customcrops
items:
  lettuce:
    enabled: true
    display_name: Lettuce
    lore:
      - "&7&oA fresh, crunchy vegetable."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/lettuce/lettuce # Link to ItemsAdder/contents/textures/item/lettuce/{filename}.png
    consumable:
      nutrition: 1
      saturation: 1