info:
  namespace: customcrops
items:
  olive_seeds:
    enabled: true
    display_name: "Olive Seeds"
    lore:
      - "&7&oPlant these seeds to grow olives."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/olive/seeds # Link to ItemsAdder/contents/textures/item/olive/{filename}.png

  olive_stage_1:
    enabled: true
    display_name: olive_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/olive/stage_1 # Link to ItemsAdder/contents/textures/item/olive/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  olive_stage_2:
    enabled: true
    display_name: olive_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/olive/stage_2 # Link to ItemsAdder/contents/textures/item/olive/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  olive_stage_3:
    enabled: true
    display_name: olive_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/olive/stage_3 # Link to ItemsAdder/contents/textures/item/olive/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  olive_stage_4:
    enabled: true
    display_name: olive_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/olive/stage_4 # Link to ItemsAdder/contents/textures/item/olive/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true