info:
  namespace: customcrops
items:
  rice_seeds:
    enabled: true
    display_name: "Rice Seeds"
    lore:
      - "&7&oPlant these seeds to grow rice."
    resource:
      material: PAPER
      generate: true
      textures:
        - item/rice/seeds # Link to ItemsAdder/contents/textures/item/rice/{filename}.png

  rice_stage_1:
    enabled: true
    display_name: rice_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/rice/stage_1 # Link to ItemsAdder/contents/textures/item/rice/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  rice_stage_2:
    enabled: true
    display_name: rice_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/rice/stage_2 # Link to ItemsAdder/contents/textures/item/rice/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  rice_stage_3:
    enabled: true
    display_name: rice_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/rice/stage_3 # Link to ItemsAdder/contents/textures/item/rice/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  rice_stage_4:
    enabled: true
    display_name: rice_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/rice/stage_4 # Link to ItemsAdder/contents/textures/item/rice/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true