info:
  namespace: customcrops
items:        
  tea_leaf_stage_1:
    enabled: true
    display_name: tea_leaf_stage_1
    resource:
      material: PAPER
      generate: false
      model_path: item/tea_leaf/stage_1 # Link to ItemsAdder/contents/textures/item/tea_leaf/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  tea_leaf_stage_2:
    enabled: true
    display_name: tea_leaf_stage_2
    resource:
      material: PAPER
      generate: false
      model_path: item/tea_leaf/stage_2 # Link to ItemsAdder/contents/textures/item/tea_leaf/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  tea_leaf_stage_3:
    enabled: true
    display_name: tea_leaf_stage_3
    resource:
      material: PAPER
      generate: false
      model_path: item/tea_leaf/stage_3 # Link to ItemsAdder/contents/textures/item/tea_leaf/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true

  tea_leaf_stage_4:
    enabled: true
    display_name: tea_leaf_stage_4
    resource:
      material: PAPER
      generate: false
      model_path: item/tea_leaf/stage_4 # Link to ItemsAdder/contents/textures/item/tea_leaf/{filename}.png
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: true