info:
  namespace: vanillaex
entities_populators:
  happy_creeper:
    entity: vanillaex:happy_creeper
    chance: 3
    spawn_logic:
      method: REPLACE
      types:
      - CREEPER
    location_range:
      y:
        min: 30
entities:
  happy_creeper:
    model_folder: entity/happy_creeper
    type: ZOMBIE
    can_sun_burn: false
    eyes_height: 0.1
    goals:
      move_to_block:
        priority: 7
        blocks:
        - POPPY
      attack_near:
        priority: 8
        entity: CREEPER
      look_at_entity:
        priority: 8
        entity: PLAYER
      melee_attack:
        priority: 10
        enabled: true
loots:
  mobs:
    happy_creeper:
      type: WOLF
      metadata:
        custom_mob_id:
          name: ItemsAdderMob
          value: vanillaex:happy_creeper
          type: string
      items:
        change_me:
          item: POPPY
          min_amount: 1
          max_amount: 3
          chance: 99.9
          ignore_fortune: false
