info:
  namespace: customdrinks
items:
    beer:
      enabled: true
      display_name: "Beer"
      lore:
        - "&7&oA popular alcoholic beverage."
      graphics:
        material: POTION
        texture: "item/beer"
      consumable:
        nutrition: 1
        saturation: 4
        can_always_eat: true
        sound: entity.generic.drink
      events:
        drink:
          increment_player_stat:
            name: thirst
            amount: 2
          potion_effect:
            type: NAUSEA
            amplifier: 1
            duration: 300
          give_item:
            item: GLASS_BOTTLE

# Recipe Section
recipes:
  crafting_table:
    beer_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: WHEAT
        B: POTION
        C: SUGAR
        D: customfoods:cask
      result:
        item: customdrinks:beer
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1