info:
  namespace: customdrinks
items:
    distilled_water:
      enabled: true
      display_name: "Distilled Water"
      lore:
        - "&7Water purified to its finest form."
      graphics:
        material: APPLE
        texture: "item/distilled_water"
      consumable:
        nutrition: 0
        saturation: 1
        can_always_eat: true
        sound: entity.generic.drink
      events:
        drink:
          increment_player_stat:
            name: thirst
            amount: 2.5
          give_item:
            item: GLASS_BOTTLE

# Recipe Section
recipes:
  cooking:
    sky_juice_recipe:
      ingredient:
        item: POTION
      machines:
        - FURNACE
      exp: 1
      cook_time: 400
      result:
        item: customdrinks:distilled_water
        amount: 1
    sky_juice_recipe_2:
      ingredient:
        item: POTION
      machines:
        - SMOKER
        - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: customdrinks:distilled_water
        amount: 1