info:
  namespace: customdrinks
items:
    melon_wine:
      enabled: true
      display_name: "Melon Wine"
      lore:
        - "&7A refreshing drink made from fermented melons."
      graphics:
        material: APPLE
        texture: "item/melon_wine"
      consumable:
        nutrition: 0
        saturation: 1
        can_always_eat: true
        sound: entity.generic.drink
      events:
        drink:
          increment_player_stat:
            name: thirst
            amount: 1
          potion_effect:
            type: NAUSEA
            amplifier: 0
            duration: 240
          give_item:
            item: GLASS_BOTTLE

# Recipe Section
recipes:
  crafting_table:
    melon_wine_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: MELON_SLICE
        B: customdrinks:distilled_water
        C: SUGAR
        D: WHEAT
        E: customfoods:cask
      result:
        item: customdrinks:melon_wine
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1