info:
  namespace: customranks
font_images:
  default: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/default.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  1: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/1.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  2: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/2.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  3: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/3.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  4: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/4.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  5: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/5.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  6: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/6.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  7: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/7.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  8: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/8.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  9: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/9.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  10: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/10.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  nub: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/nub.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  nubest: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/nubest.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  helper: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/helper.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  builder: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/builder.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  vip: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/vip.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  vipplus: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/vipplus.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  mod: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/mod.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value
  admin: # This will match with the luckperm's {groupname} and {groupname}.png
    permission_suffix: "ranks"
    show_in_gui: true
    suggest_in_command: false
    path: "font/admin.png"
    scale_ratio: 9 # Do not change this value
    y_position: 8 # Do not change this value