info:
  namespace: customranks
items:
  level_1:
    display_name: "Level 1"
    lore:
      - "&7&oConsume to rank up!"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/1
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true