info:
  namespace: customranks
items:
  level_1:
    display_name: "Level 1"
    lore:
      - "&7&oShows you are a Level 1 player!"
      - "&7&oCannot be obtained any other way!"
    resource:
      material: PAPER
      generate: true
      textures:
        - font/1.png