info:
  namespace: customranks
items:
  level_8:
    display_name: "Level 8"
    lore:
      - "&7&oShows you are a Level 8 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/8.png