info:
  namespace: customranks
items:
  level_5:
    display_name: "Level 5"
    lore:
      - "&7&oShows you are a Level 5 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/5.png