info:
  namespace: customranks
items:
  level_6:
    display_name: "Level 6"
    lore:
      - "&7&oShows you are a Level 6 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/6.png