info:
  namespace: customranks
items:
  level_7:
    display_name: "Level 7"
    lore:
      - "&7&oShows you are a Level 7 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/7.png