info:
  namespace: customranks
items:
  level_2:
    display_name: "Level 2"
    lore:
      - "&7&oShows you are a Level 2 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/2.png