info:
  namespace: customranks
items:
  level_3:
    display_name: "Level 3"
    lore:
      - "&7&oShows you are a Level 3 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/3.png