info:
  namespace: customranks
items:
  level_9:
    display_name: "Level 9"
    lore:
      - "&7&oShows you are a Level 9 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/9.png