info:
  namespace: customranks
items:
  level_10:
    display_name: "Level 10"
    lore:
      - "&7&oShows you are a Level 10 player!"
      - "&7&oCannot be obtained any other way!"
    graphics:
      textures:
        layer0: font/10.png