info:
  namespace: customfoods
items:
  apple_cake:
    enabled: true
    name: "Apple Cake"
    lore:
      - "&7A sweet & fruity apple cake."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/apple_cake
    consumable:
      nutrition: 9
      saturation: 10
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: HEALTH_BOOST
          amplifier: 0
          duration: 600

# Recipe Section
recipes:
  crafting_table:
    apple_cake_recipe:
      enabled: true
      pattern:
        - CAG
        - BDF
        - EEE
      ingredients:
        A: customfoods:flour
        B: customfoods:butter
        C: customfoods:oven
        D: APPLE
        E: customfoods:milk_cream
        F: SUGAR
        G: EGG
      result:
        item: customfoods:apple_cake
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1