info:
  namespace: customfoods
items:
  bagel:
    enabled: true
    name: "Bagel"
    lore:
      - "&7&oA round bread roll with a hole in the middle."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/bagel
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    bagel_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: customfoods:salt
        C: customfoods:oven
      result:
        item: customfoods:bagel
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1