info:
  namespace: customfoods
items:
  baguette:
    enabled: true
    name: "Baguette"
    lore:
      - "&7&oA long, thin loaf of French bread."
      - ""
      - "&5When consumed:"
      - "&9Slow Fall - 5s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/baguette
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: SLOW_FALLING
            amplifier: 0
            duration: 100

# Recipe Section
recipes:
  crafting_table:
    baguette_recipe:
      enabled: true
      pattern:
        - CAX
        - BAX
        - XAX
      ingredients:
        A: customfoods:dough
        B: customfoods:salt
        C: customfoods:oven
      result:
        item: customfoods:baguette
        amount: 3
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1