info:
  namespace: customfoods
items:
  beet_sandwich:
    enabled: true
    name: "Beet Sandwich"
    lore:
      - "&7A delicious beet sandwich."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/beet_sandwich
    consumable:
      nutrition: 6
      saturation: 6
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    beet_sandwich_recipe:
      enabled: true
      pattern:
        - XAX
        - CBD
        - XAX
      ingredients:
        A: customfoods:white_bread_slice
        B: BEETROOT
        C: customcrops:lettuce
        D: customfoods:cheese_slice
      result:
        item: customfoods:beet_sandwich
        amount: 1