info:
  namespace: customfoods
items:
  burger:
    enabled: true
    display_name: Burger
    lore:
      - "&7&oA juicy beef patty with fresh toppings."
      - ""
      - "&5When consumed:"
      - "&9Regeneration - 5s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/burger
    consumable:
      nutrition: 10
      saturation: 10
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: REGENERATION
            amplifier: 1
            duration: 100

# Recipe Section
recipes:
  crafting_table:
    burger_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:burger_bun
        B: customfoods:frying_pan
        C: customcrops:tomato
        D: customcrops:lettuce
        E: COOKED_BEEF
        F: customfoods:cheese_slice
      result:
        item: customfoods:burger
        amount: 2
      return_items:
        decrement_durability:
          frying_pan:
            item: customfoods:frying_pan
            amount: 1
        play_sound:
          name: customsounds:frying_pan
          volume: 1
          pitch: 1