info:
  namespace: customfoods
items:
  burger_bun:
    enabled: true
    name: "Burger Bun"
    lore:
      - "&7A soft round bun for burgers."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/burger_bun
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    burger_bun_recipe:
      enabled: true
      pattern:
        - CAX
        - BAX
        - XXX
      ingredients:
        A: customfoods:dough
        B: customfoods:salt
        C: customfoods:oven
      result:
        item: customfoods:burger_bun
        amount: 2
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1