info:
  namespace: customfoods
items:
  burger:
    enabled: true
    display_name: Burger
    lore:
      - "&7&oA delicious burger with all the toppings."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/burger
    consumable:
      nutrition: 7
      saturation: 7
      can_always_eat: true