info:
  namespace: customfoods
items:
  burrito:
    enabled: true
    name: "Burrito"
    lore:
      - "&7A delicious burrito filled with ingredients."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/burrito
    consumable:
      nutrition: 7
      saturation: 8
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: STRENGTH
          amplifier: 0
          duration: 200

# Recipe Section
recipes:
  crafting_table:
    burrito_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: customfoods:cheese
        C: COOKED_CHICKEN # H6 S7.2
        D: customcrops:corn
        E: customcrops:tomato
        F: customfoods:frying_pan
      result:
        item: customfoods:burrito
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:frying_pan
            amount: 1
        replace:
          HONEY_BOTTLE: GLASS_BOTTLE
        play_sound:
          name: customsounds:frying_pan
          volume: 1
          pitch: 1