info:
  namespace: customfoods
items:
  butter:
    enabled: true
    display_name: Butter
    lore:
      - "&7&oA creamy dairy product."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/butter
    consumable:
      nutrition: 1
      saturation: 1
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: HUNGER
            amplifier: 0
            duration: 240

# Recipe Section
recipes:
  crafting_table:
    butter_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: MILK_BUCKET
        B: customfoods:salt
        C: customfoods:cask
      result:
        item: customfoods:butter
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        replace:
          MILK_BUCKET: BUCKET
          customfoods:salt: customfoods:milk_cream
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1