info:
  namespace: customfoods
items:
  cheese_slice:
    enabled: true
    display_name: Cheese Slice
    lore:
      - "&7A thin slice of cheese."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/cheese_slice
    consumable:
      nutrition: 1
      saturation: 1
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    cheese_slice_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:cheese
        B: customfoods:knife
      result:
        item: customfoods:cheese_slice
        amount: 3
      return_items:
        decrement_durability:
          knife:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1
