info:
  namespace: customfoods
items:
  cheese:
    enabled: true
    display_name: Cheese
    lore:
      - "&7A creamy dairy product made from milk."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/cheese
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    cheese_recipe:
      enabled: true
      shapeless: true
      ingredients:
        M: MILK_BUCKET
        S: customfoods:salt
        V: customfoods:vinegar
        C: customfoods:cask
      result:
        item: customfoods:cheese
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        replace:
          MILK_BUCKET: BUCKET
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1
