info:
  namespace: customfoods
items:
  cherry_tart:
    enabled: true
    name: "Cherry Tart"
    lore:
      - "&7A sweet and fruity dessert."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/cherry_tart
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: RESISTANCE
          amplifier: 0
          duration: 120

# Recipe Section
recipes:
  crafting_table:
    cherry_tart_recipe:
      enabled: true
      pattern:
        - CDX
        - ABA
        - XAX
      ingredients:
        A: customfoods:dough
        B: customcrops:cherry
        C: customfoods:oven
        D: SUGAR
      result:
        item: customfoods:cherry_tart
        amount: 3
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1