info:
  namespace: customfoods
items:
  chicken_sandwich:
    enabled: true
    name: "Chicken Sandwich"
    lore:
      - "&7A delicious chicken sandwich."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/chicken_sandwich
    consumable:
      nutrition: 8
      saturation: 8
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    chicken_sandwich_recipe:
      enabled: true
      pattern:
        - XAX
        - XBX
        - XAX
      ingredients:
        A: customfoods:white_bread_slice
        B: COOKED_CHICKEN
      result:
        item: customfoods:chicken_sandwich
        amount: 2