info:
  namespace: customfoods
items:
  chicken_nugget:
    enabled: true
    display_name: "Chicken Nugget"
    lore:
      - "&7Crispy and delicious chicken nuggets."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/chicken_nugget
    consumable:
      nutrition: 4
      saturation: 4.4
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    chicken_nugget_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: COOKED_CHICKEN
        B: customfoods:salt
        C: customfoods:knife
      result:
        item: customfoods:chicken_nugget
        amount: 2
      return_items:
        decrement_durability:
          knife:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1