info:
  namespace: customfoods
items:
  chocolate_swiss_roll:
    enabled: true
    name: "Chocolate Swiss Roll"
    lore:
      - "&7A delicious chocolate cake roll."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/chocolate_swiss_roll
    consumable:
      nutrition: 7
      saturation: 8
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: LUCK
          amplifier: 0
          duration: 200

# Recipe Section
recipes:
  crafting_table:
    chocolate_swiss_roll_recipe:
      enabled: true
      pattern:
        - CAX
        - ABA
        - XAX
      ingredients:
        A: customfoods:dough
        B: customfoods:chocolate
        C: customfoods:oven
      result:
        item: customfoods:chocolate_swiss_roll
        amount: 4
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1