info:
  namespace: customfoods
items:
  chocolate:
    enabled: true
    display_name: Chocolate
    lore:
      - "&7&oA sweet treat made from cocoa."
      - ""
      - "&5When consumed:"
      - "&9Luck - 10s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/chocolate
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true
    events:
      drink:
        potion_effect:
          type: LUCK
          amplifier: 0
          duration: 200

# Recipe Section
recipes:
  crafting_table:
    chocolate_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: COCOA_BEANS
        B: SUGAR
        C: customfoods:cask
      result:
        item: customfoods:chocolate
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1
