info:
  namespace: customfoods
items:
  croissant:
    enabled: true
    name: "Croissant"
    lore:
      - "&7&oA flaky & layered buttery pastry."
      - ""
      - "&5When consumed:"
      - "&9Haste - 5s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/croissant
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: HASTE
            amplifier: 0
            duration: 100

# Recipe Section
recipes:
  crafting_table:
    croissant_recipe:
      enabled: true
      pattern:
        - CAX
        - ABA
        - XXX
      ingredients:
        A: customfoods:dough
        B: customfoods:butter
        C: customfoods:oven
      result:
        item: customfoods:croissant
        amount: 3
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1