info:
  namespace: customfoods
items:
  croissant:
    enabled: true
    name: "Croissant"
    lore:
      - "&7&oA flaky & layered buttery pastry."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/croissant
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    croissant_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: customfoods:dough
        C: customfoods:butter
        D: customfoods:oven
      result:
        item: customfoods:croissant
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1