info:
  namespace: customfoods
items:
  donut:
    enabled: true
    name: "Donut"
    lore:
      - "&7A sweet, deep-fried pastry."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/donut
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: JUMP_BOOST
          amplifier: 0
          duration: 100

# Recipe Section
recipes:
  crafting_table:
    donut_recipe:
      enabled: true
      pattern:
        - CAD
        - ABA
        - XAX
      ingredients:
        A: customfoods:dough
        B: SUGAR
        C: customfoods:fryer
        D: customfoods:oil
      result:
        item: customfoods:donut
        amount: 4
      return_items:
        decrement_durability:
          oven:
            item: customfoods:fryer
            amount: 1
        play_sound:
          name: customsounds:fryer
          volume: 1
          pitch: 1