info:
  namespace: customfoods
items:
  dough:
    enabled: true
    display_name: Dough
    lore:
      - "&7&oA soft and pliable mixture used for baking."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/dough
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: HUNGER
            amplifier: 1
            duration: 240

# Recipe Section
recipes:
  crafting_table:
    dough:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:flour
        B: POTION
        C: EGG
      result:
        item: customfoods:dough
        amount: 2
      return_items:
        replace:
          POTION: GLASS_BOTTLE