info:
  namespace: customfoods
items:
  flour:
    enabled: true
    name: Flour
    lore:
      - "&7A fine powder made from grinding wheat."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/flour
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: SLOWNESS
          amplifier: 0
          duration: 240

# Recipe Section
recipes:
  crafting_table:
    flour_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: HAY_BLOCK
        B: customfoods:grinder
      result:
        item: customfoods:flour
        amount: 3
      return_items:
        decrement_durability:
          grinder:
            item: customfoods:grinder
            amount: 1
        play_sound:
          name: customsounds:grinder
          volume: 1
          pitch: 1