info:
  namespace: customfoods
items:
  fries:
    enabled: true
    display_name: Fries
    lore:
      - "&7Who doesn't love fries?"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/fries
    consumable:
      nutrition: 4
      saturation: 4.2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    fries:
      enabled: true
      shapeless: true
      ingredients:
        A: BAKED_POTATO # H5 S6
        B: customfoods:salt # H0.2 S0.2
        C: customfoods:knife
      result:
        item: customfoods:fries
        amount: 2
      return_items:
        decrement_durability:
          knife:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1