info:
  namespace: customfoods
items:
  ikura_maki:
    enabled: true
    display_name: Ikura Maki
    lore:
      - "&7A delicious sushi roll filled with fresh salmon roe."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/ikura_maki
    consumable:
      nutrition: 6
      saturation: 6
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    ikura_maki_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:rice
        B: customfoods:salt
        C: DRIED_KELP
        D: customfishes:roe
        E: customfoods:sushi_rolling_mat
      result:
        item: customfoods:ikura_maki
        amount: 1
      return_items:
        decrement_durability:
          frying_pan:
            item: customfoods:sushi_rolling_mat
            amount: 1
        play_sound:
          name: customsounds:sushi_rolling_mat
          volume: 1
          pitch: 1