info:
  namespace: customfoods
items:
  grinder:
    enabled: true
    display_name: "Grinder"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/grinder
    durability:
      max_durability: 100
      disappear_when_broken: true

  knife:
    enabled: true
    display_name: "Knife"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/knife
    durability:
      max_durability: 100
      disappear_when_broken: true

  frying_pan:
    enabled: true
    display_name: "Frying Pan"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/frying_pan
    durability:
      max_durability: 100
      disappear_when_broken: true

  cooking_pot:
    enabled: true
    display_name: "Cooking Pot"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/cooking_pot
    durability:
      max_durability: 100
      disappear_when_broken: true

  food_press:
    enabled: true
    display_name: "Food Press"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/food_press
    durability:
      max_durability: 100
      disappear_when_broken: true
  
  cask:
    enabled: true
    display_name: "Cask"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/cask
    durability:
      max_durability: 100
      disappear_when_broken: true
  
  fryer:
    enabled: true
    display_name: "Fryer"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/fryer
    durability:
      max_durability: 100
      disappear_when_broken: true
  
  oven:
    enabled: true
    display_name: "Oven"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/oven
    durability:
      max_durability: 100
      disappear_when_broken: true

  sushi_rolling_mat:
    enabled: true
    display_name: "Sushi Rolling Mat"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/sushi_rolling_mat
    durability:
      max_durability: 100
      disappear_when_broken: true

# Recipe Section
recipes:
  crafting_table:
    knife_recipes:
      enabled: true
      pattern:
        - XA
        - BX
      ingredients:
        A: IRON_INGOT
        B: STICK
      result:
        item: customfoods:knife
        amount: 1
    grinder_recipes:
      enabled: true
      pattern:
        - XAX
        - ABA
        - XAX
      ingredients:
        A: IRON_INGOT
        B: HOPPER
      result:
        item: customfoods:grinder
        amount: 1
    frying_pan_recipes:
      enabled: true
      pattern:
        - XAX
        - AAA
        - BAX
      ingredients:
        A: IRON_INGOT
        B: STICK
      result:
        item: customfoods:frying_pan
        amount: 1
    cooking_pot_recipes:
      enabled: true
      pattern:
        - BXB
        - AXA
        - AAA
      ingredients:
        A: IRON_INGOT
        B: IRON_NUGGET
      result:
        item: customfoods:cooking_pot
        amount: 1
    food_press_recipes:
      enabled: true
      pattern:
        - AX
        - BX
      ingredients:
        A: PISTON
        B: HOPPER
      result:
        item: customfoods:food_press
        amount: 1
    cask_recipes:
      enabled: true
      pattern:
        - AAA
        - BXB
        - AAA
      ingredients:
        A: OAK_PLANKS
        B: IRON_INGOT
      result:
        item: customfoods:cask
        amount: 1
    fryer_recipes:
      enabled: true
      pattern:
        - CAC
        - ABA
        - CAC
      ingredients:
        A: IRON_INGOT
        B: HOPPER
        C: REDSTONE
      result:
        item: customfoods:fryer
        amount: 1
    oven_recipes:
      enabled: true
      pattern:
        - BAB
        - ACA
        - BAB
      ingredients:
        A: IRON_BLOCK
        B: IRON_INGOT
        C: REDSTONE_BLOCK
      result:
        item: customfoods:oven
        amount: 1
    sushi_rolling_mat_recipes:
      enabled: true
      pattern:
        - AAA
        - BAB
        - AAA
      ingredients:
        A: BAMBOO
        B: STRING
      result:
        item: customfoods:sushi_rolling_mat
        amount: 1