info:
  namespace: customfoods
items:
  lemon_tart:
    enabled: true
    name: "Lemon Tart"
    lore:
      - "&7&oA sweet and tangy dessert."
      - ""
      - "&5When consumed:"
      - "&9Resistance - 6s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/lemon_tart
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: RESISTANCE
            amplifier: 0
            duration: 120

# Recipe Section
recipes:
  crafting_table:
    lemon_tart_recipe:
      enabled: true
      pattern:
        - CDX
        - ABA
        - XAX
      ingredients:
        A: customfoods:dough
        B: customcrops:lemon
        C: customfoods:oven
        D: SUGAR
      result:
        item: customfoods:lemon_tart
        amount: 3
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1