info:
  namespace: customfoods
items:
    melon_wine:
      enabled: true
      display_name: "Melon Wine"
      lore:
        - "&7&oA refreshing drink made from fermented melons."
      resource:
        material: POTION
        generate: true
        textures:
          - item/melon_wine
      consumable:
        nutrition: 6
        saturation: 0
        can_always_eat: true
        sound: entity.generic.drink
      events:
        drink:
          potion_effect:
            type: NAUSEA
            amplifier: 1
            duration: 240
          give_item:
            item: GLASS_BOTTLE
          


# Recipe Section
recipes:
  crafting_table:
    melon_wine_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: MELON_SLICE
        B: POTION
        C: SUGAR
        D: WHEAT
        E: customfoods:cask
      result:
        item: customfoods:melon_wine
        amount: 1
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1