info:
  namespace: customfoods
items:
  milk_cream:
    enabled: true
    display_name: Milk Cream
    lore:
      - "&7A rich and creamy dairy product."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/milk_cream
    consumable:
      nutrition: 0
      saturation: 0
      can_always_eat: true
      sound: entity.generic.drink
    events:
      drink:
        execute_commands:
          command_1:
            command: minecraft:effect clear {player}
            as_console: true
            delay: 1