info:
  namespace: customfoods
items:
  muffin:
    enabled: true
    name: "Muffin"
    lore:
      - "&7A small, round baked good."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/muffin
    consumable:
      nutrition: 6
      saturation: 7
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    muffin_recipe:
      enabled: true
      pattern:
        - CAD
        - EBX
        - XXX
      ingredients:
        A: customfoods:dough
        B: customfoods:butter
        C: customfoods:oven
        D: SUGAR
        E: customfoods:milk_cream
      result:
        item: customfoods:muffin
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1