info:
  namespace: customfoods
items:
  sake_nigiri:
    enabled: true
    display_name: Sake Nigiri
    lore:
      - "&7A classic sushi rice topped with fresh salmon."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/sake_nigiri
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    sake_nigiri_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:rice
        B: customfoods:salt
        C: SALMON
        D: customfoods:sushi_rolling_mat
      result:
        item: customfoods:sake_nigiri
        amount: 3
      return_items:
        decrement_durability:
          frying_pan:
            item: customfoods:sushi_rolling_mat
            amount: 1
        play_sound:
          name: customsounds:sushi_rolling_mat
          volume: 1
          pitch: 1