info:
  namespace: customfoods
items:
  nigiri:
    enabled: true
    display_name: Nigiri
    lore:
      - "&7&oA Japanese dish consisting of rice and raw fish."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/nigiri
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    nigiri_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:rice
        B: customfoods:salt
        C: SALMON
        D: DRIED_KELP
      result:
        item: customfoods:nigiri
        amount: 3