info:
  namespace: customfoods
items:
  noodle:
    enabled: true
    display_name: Noodle
    lore:
      - "&7&oA long, thin strip of pasta."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/noodle
    consumable:
      nutrition: 5
      saturation: 6
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: HUNGER
            amplifier: 0
            duration: 240

# Recipe Section
recipes:
  crafting_table:
    noodle_recipe:
      enabled: true
      pattern:
        - AXX
        - XXX
        - XXX
      ingredients:
        A: customfoods:dough
      result:
        item: customfoods:noodle
        amount: 1