info:
  namespace: customfoods
items:
  oil:
    enabled: true
    display_name: Oil
    lore:
      - "&7&oA liquid fat used for cooking."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/oil
    consumable:
      nutrition: 0
      saturation: 0
      can_always_eat: true
      sound: entity.generic.drink
    events:
        drink:
          potion_effect:
            type: SLOWNESS
            amplifier: 0
            duration: 240

# Recipe Section
recipes:
  crafting_table:
    oil:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:olive
        B: customfoods:grinder
      result:
        item: customfoods:oil
        amount: 1
      return_items:
        decrement_durability:
          grinder:
            item: customfoods:grinder
            amount: 1
        play_sound:
          name: customsounds:grinder
          volume: 1
          pitch: 1