info:
  namespace: customfoods
items:
  onigiri:
    enabled: true
    display_name: Onigiri
    lore:
      - "&7&oA Japanese rice ball, often wrapped in seaweed."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/onigiri
    consumable:
      nutrition: 5
      saturation: 4
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    onigiri_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:rice
        B: customfoods:salt
        C: DRIED_KELP
      result:
        item: customfoods:onigiri
        amount: 3