info:
  namespace: customfoods
items:
  onion_ring:
    enabled: true
    display_name: Onion Ring
    lore:
      - "&7&oCrispy and delicious onion rings."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/onion_ring
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    onion_ring_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:onion
        B: customfoods:salt
        C: customfoods:fryer
        D: customfoods:oil
      result:
        item: customfoods:onion_ring
        amount: 2
      return_items:
        decrement_durability:
          fryer:
            item: customfoods:fryer
            amount: 1
        play_sound:
          name: customsounds:fryer
          volume: 1
          pitch: 1