info:
  namespace: customfoods
items:
  popcorn:
    enabled: true
    display_name: Popcorn
    lore:
      - "&7A delicious snack made from popped corn."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/popcorn
    consumable:
      nutrition: 4
      saturation: 4
      can_always_eat: true

# Recipe Section
recipes:
  cooking:
    popcorn:
      ingredient:
        item: customcrops:corn
      machines:
        - FURNACE
        - SMOKER
      exp: 0.5
      cook_time: 800
      result:
        item: customfoods:popcorn
        amount: 1