info:
  namespace: customfoods
items:
  salmonsashimi:
    enabled: true
    display_name: Salmon Sashimi
    lore:
      - "&7&oA delicacy made from fresh salmon, served raw."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/salmonsashimi
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    salmonsashimi:
      enabled: true
      shapeless: true
      ingredients:
        A: SALMON
        B: customfoods:knife
      result:
        item: customfoods:salmonsashimi
        amount: 2
      return_items:
        decrement_durability:
          knife:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1