info:
  namespace: customfoods
items:
  salt:
    enabled: true
    display_name: Salt
    lore:
      - "&7Perfect for seasoning your food!"
    resource:
      material: PAPER
      generate: true
      textures:
        - item/salt
    consumable:
      nutrition: 0.2
      saturation: 0.2
      can_always_eat: true
    

# Recipe Section
recipes:
  cooking:
    salt:
      ingredient:
        item: POTION
      machines:
        - FURNACE
        - SMOKER
      exp: 1
      cook_time: 800
      result:
        item: customfoods:salt
        amount: 32