info:
  namespace: customfoods
items:
  scrambled_egg:
    enabled: true
    display_name: Scrambled Egg
    lore:
      - "&7A delicious scrambled egg dish."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/scrambled_egg
    consumable:
      nutrition: 4
      saturation: 4
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    scrambled_egg:
      enabled: true
      shapeless: true
      ingredients:
        A: EGG
        B: customfoods:salt
        C: customfoods:frying_pan
      result:
        item: customfoods:scrambled_egg
        amount: 1
      return_items:
        decrement_durability:
          frying_pan:
            item: customfoods:frying_pan
            amount: 1
        play_sound:
          name: customsounds:frying_pan
          volume: 1
          pitch: 1