info:
  namespace: customfoods
items:
  soysauce:
    enabled: true
    display_name: Soy Sauce
    lore:
      - "&7A savory sauce made from fermented soybeans."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/soysauce
    consumable:
      nutrition: 0
      saturation: 0
      can_always_eat: true
      sound: entity.generic.drink

# Recipe Section
recipes:
  crafting_table:
    soysauce_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:soybean
        B: customfoods:cask
      result:
        item: customfoods:soysauce
        amount: 2
      return_items:
        decrement_durability:
          cask:
            item: customfoods:cask
            amount: 1
        play_sound:
          name: customsounds:cask
          volume: 1
          pitch: 1