info:
  namespace: customfoods
items:
  soysauce:
    enabled: true
    display_name: Soy Sauce
    lore:
      - "&7&oA savory sauce made from fermented soybeans."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/soysauce
    consumable:
      nutrition: 0
      saturation: 0
      can_always_eat: true
      sound: entity.generic.drink

# Recipe Section
recipes:
  cooking:
    soysauce:
      ingredient:
        item: customcrops:soybean
      machines:
        - FURNACE
        - SMOKER
      exp: 1
      cook_time: 200
      result:
        item: customfoods:soysauce
        amount: 8