info:
  namespace: customfoods
items:
  taco:
    enabled: true
    display_name: Taco
    lore:
      - "&7A delicious taco filled with seasoned meat and vegetables."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/taco
    consumable:
      nutrition: 8
      saturation: 12
      can_always_eat: true
    events:
      eat:
        potion_effect:
          type: STRENGTH
          amplifier: 0
          duration: 200

# Recipe Section
recipes:
  crafting_table:
    taco:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: customfoods:salt
        C: COOKED_BEEF # H8 S12.8
        D: customcrops:tomato
        E: customcrops:lettuce
        F: customfoods:oven
      result:
        item: customfoods:frying_pan
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:frying_pan
            amount: 1
        play_sound:
          name: customsounds:frying_pan
          volume: 1
          pitch: 1