info:
  namespace: customfoods
items:
  taco:
    enabled: true
    display_name: Taco
    lore:
      - "&7&oA delicious taco filled with seasoned meat and vegetables."
      - ""
      - "&5When consumed:"
      - "&9Strength - 10s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/taco
    consumable:
      nutrition: 8
      saturation: 12
      can_always_eat: true
    events:
        eat:
          potion_effect:
            type: STRENGTH
            amplifier: 1
            duration: 200

# Recipe Section
recipes:
  crafting_table:
    taco:
      enabled: true
      shapeless: true
      ingredients:
        A: BREAD
        B: customfoods:salt
        C: COOKED_BEEF # H8 S12.8
        D: customcrops:tomato
        E: customcrops:lettuce
        F: customfoods:oven
      result:
        item: customfoods:taco
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1