info:
  namespace: customfoods
items:
  tamago_nigiri:
    enabled: true
    display_name: Tamago Nigiri
    lore:
      - "&7A delicious sushi rice topped with sweet omelette."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/tamago_nigiri
    consumable:
      nutrition: 6
      saturation: 6
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    tamago_nigiri_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customcrops:rice
        B: customfoods:salt
        C: DRIED_KELP
        D: EGG
        E: customfoods:sushi_rolling_mat
      result:
        item: customfoods:tamago_nigiri
        amount: 1
      return_items:
        decrement_durability:
          frying_pan:
            item: customfoods:sushi_rolling_mat
            amount: 1
        play_sound:
          name: customsounds:sushi_rolling_mat
          volume: 1
          pitch: 1