info:
  namespace: customfoods
items:
  veggie_pizza:
    enabled: true
    display_name: Veggie Pizza
    lore:
      - "&7&oA delicious pizza topped with fresh vegetables."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/veggie_pizza
    consumable:
      nutrition: 10
      saturation: 10
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    veggie_pizza:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: customfoods:cheese
        C: customcrops:tomato
        D: customcrops:bellpepper
        E: BROWN_MUSHROOM
        F: customcrops:onion
        G: customfoods:oven
      result:
        item: customfoods:veggie_pizza
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1