info:
  namespace: customfoods
items:
  vinegar:
    enabled: true
    display_name: Vinegar
    lore:
      - "&7Perfect for seasoning your food!"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/vinegar
    consumable:
      nutrition: 0
      saturation: 1
      can_always_eat: true
      sound: entity.generic.drink
    events:
      eat:
        potion_effect:
          type: NAUSEA
          amplifier: 0
          duration: 120
    
# Recipe Section
recipes:
  cooking:
    vinegar:
      ingredient:
        item: MELON_SLICE
      machines:
        - FURNACE
        - SMOKER
      exp: 1
      cook_time: 800
      result:
        item: customfoods:vinegar
        amount: 1