info:
  namespace: customfoods
items:
  waffle:
    enabled: true
    name: "Waffle"
    lore:
      - "&7&oA square-shaped breakfast treat."
      - ""
      - "&5When consumed:"
      - "&9Night Vision - 10s"
    resource:
      material: APPLE
      generate: true
      textures:
        - item/waffle
    consumable:
      nutrition: 7
      saturation: 7
      can_always_eat: true
    events:
        drink:
          potion_effect:
            type: NIGHT_VISION
            amplifier: 1
            duration: 100

# Recipe Section
recipes:
  crafting_table:
    waffle_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:dough
        B: SUGAR
        C: customfoods:oven
        D: HONEY_BOTTLE
        E: customfoods:butter
      result:
        item: customfoods:waffle
        amount: 3
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        replace:
          HONEY_BOTTLE: GLASS_BOTTLE
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1