info:
  namespace: customfoods
items:
  white_bread:
    enabled: true
    name: "White Bread"
    lore:
      - "&7A soft loaf of white bread."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/white_bread
    consumable:
      nutrition: 10
      saturation: 11
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    white_bread_recipe:
      enabled: true
      pattern:
        - CAX
        - BAX
        - XXX
      ingredients:
        A: customfoods:dough
        B: SUGAR
        C: customfoods:oven
      result:
        item: customfoods:white_bread
        amount: 1
      return_items:
        decrement_durability:
          oven:
            item: customfoods:oven
            amount: 1
        play_sound:
          name: customsounds:oven
          volume: 1
          pitch: 1