info:
  namespace: customfoods
items:
  white_bread_slice:
    enabled: true
    display_name: White Bread Slice
    lore:
      - "&7A thin slice of white bread."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/white_bread_slice
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    white_bread_slice_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfoods:white_bread
        B: customfoods:knife
      result:
        item: customfoods:white_bread_slice
        amount: 5
      return_items:
        decrement_durability:
          knife:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1
