info:
  namespace: customsounds
minecraft_lang_overwrite:
  my_lang_overwrite:
    entries:
      sound.knife: "Knife Sound"
      sound.grinder: "Grinder Sound"
      sound.cooking_pot: "Cooking Pot Sound"
      sound.frying_pan: "Frying Pan Sound"
      sound.cask: "Cask Sound"
      sound.oven: "Oven Sound"
      sound.fryer: "Fryer Sound"
      sound.food_press: "Food Press Sound"
      sound.sushi_rolling_mat: "Sushi Rolling Mat Sound"
    languages:
    - ALL
sounds:
  knife:
    path: knife
    settings:
      subtitle: sound.knife
  grinder:
    path: grinder
    settings:
      subtitle: sound.grinder
  cooking_pot:
    path: cooking_pot
    settings:
      subtitle: sound.cooking_pot
  frying_pan:
    path: frying_pan
    settings:
      subtitle: sound.frying_pan
  cask:
    path: cask
    settings:
      subtitle: sound.cask
  oven:
    path: oven
    settings:
      subtitle: sound.oven
  fryer:
    path: fryer
    settings:
      subtitle: sound.fryer
  food_press:
    path: food_press
    settings:
      subtitle: sound.food_press
  sushi_rolling_mat:
    path: sushi_rolling_mat
    settings:
      subtitle: sound.sushi_rolling_mat