info:
  namespace: customfishes
items:
  anchovy:
    enabled: true
    name: "Anchovy"
    lore:
      - "&7Small and tasty fish, great for cooking."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/anchovy
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    anchovy_loots:
      # biomes:
      #   - WARM_OCEAN
      items:
        item_1:
          item: customfishes:anchovy
          min_amount: 1
          max_amount: 1
          chance: 8