info:
  namespace: customfishes
items:
  calamari:
    enabled: true
    name: "Calamari"
    lore:
      - "&7A part from a squid, often served fried."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/calamari
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    calamari_loots:
      items:
        item_1:
          item: customfishes:calamari
          min_amount: 1
          max_amount: 1
          chance: 8