info:
  namespace: customfishes
items:
  crab_legs:
    enabled: true
    name: "Crab Legs"
    lore:
      - "&7A tasty crab leg, perfect for a seafood feast."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/crab_legs
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

# Recipe Section
recipes:
  crafting_table:
    crab_legs_recipe:
      enabled: true
      shapeless: true
      ingredients:
        A: customfishes:crab
        B: customfoods:knife
      result:
        item: customfishes:crab_legs
        amount: 2
      return_items:
        decrement_durability:
          oven:
            item: customfoods:knife
            amount: 1
        play_sound:
          name: customsounds:knife
          volume: 1
          pitch: 1