info:
  namespace: customfishes
items:
  frog_legs:
    enabled: true
    name: "Frog Legs"
    lore:
      - "&7A part from a frog, often served fried."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/frog_legs
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    frog_legs_loots:
      items:
        item_1:
          item: customfishes:frog_legs
          min_amount: 1
          max_amount: 1
          chance: 8