info:
  namespace: customfishes
items:
  glowing_calamari:
    enabled: true
    name: "Glowing Calamari"
    lore:
      - "&7A part from a squid, often served fried."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/glowing_calamari
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    glowing_calamari_loots:
      items:
        item_1:
          item: customfishes:glowing_calamari
          min_amount: 1
          max_amount: 1
          chance: 8