info:
  namespace: customfishes
items:
  oyster:
    enabled: true
    name: "Oyster"
    lore:
      - "&7A bivalve mollusk found in saltwater."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/oyster
    consumable:
      nutrition: 2
      saturation: 2
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    oyster_loots:
      items:
        item_1:
          item: customfishes:oyster
          min_amount: 1
          max_amount: 1
          chance: 8