info:
  namespace: customfishes
items:
  roe:
    enabled: true
    name: "Roe"
    lore:
      - "&7Fresh fish eggs, a delicacy in many cuisines."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/roe
    consumable:
      nutrition: 5
      saturation: 5
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    roe_loots:
      # biomes:
      #   - WARM_OCEAN
      items:
        item_1:
          item: customfishes:roe
          min_amount: 1
          max_amount: 5
          chance: 5