info:
  namespace: customfishes
items:
  tuna:
    enabled: true
    name: "Tuna"
    lore:
      - "&7A large and valuable fish, great for cooking."
    resource:
      material: APPLE
      generate: true
      textures:
        - item/tuna
    consumable:
      nutrition: 6
      saturation: 6
      can_always_eat: true

#Loot Table Section
loots:
  fishing:
    tuna_loots:
      items:
        item_1:
          item: customfishes:tuna
          min_amount: 1
          max_amount: 1
          chance: 3